import type { NextPage } from 'next'
import Head from 'next/head'
import { ReactNode } from 'react'
import { MessageList } from '../src/components/messageList'
import { useMessages } from '../src/resources/message'

const Home: NextPage = () => {
  const { isLoading, isSuccess, data } = useMessages()

  if (isLoading) return withHeader('Loading...')

  if (isSuccess) return withHeader(<MessageList messages={data} />)

  return withHeader('Error')
}

const withHeader = (body: ReactNode) => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {body}
  </div>
)

export default Home
