import type { NextPage } from 'next'
import Head from 'next/head'
import { ReactNode } from 'react'
import { MessageList } from '../src/components/messageList'
import { useMessages } from '../src/resources/message'
import { useSession, signIn, signOut } from 'next-auth/react'

const Home: NextPage = () => {
  const { data: session } = useSession()
  const { isLoading, isSuccess, data } = useMessages()

  const maybeSessionSection = session ? (
    <>
      Signed in as {session.user.username} <br />
      <button onClick={() => signOut()}>Sign out</button>
    </>
  ) : (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  )

  const withHeader = (body: ReactNode) => (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {maybeSessionSection}
      <br />
      {body}
    </div>
  )

  if (isLoading) return withHeader('Loading...')

  if (isSuccess) return withHeader(<MessageList messages={data} />)

  return withHeader('Error')
}

export default Home
